main: fr.shykuzo.punishment.Main

author: Shykuzo

name: ${project.name}
description: ${project.description}

version: ${project.version}
website: ${project.url}

commands:
   ban:
      description: "Ban a player temporarily or permanently."