main: fr.shykuzo.punishment.Main

author: Shykuzo

name: ${project.name}
description: ${project.description}

version: ${project.version}
website: ${project.url}

commands:
   punishment:
      description: "Manage Plugin"

   ban:
      description: "Ban a player temporarily or permanently."
   unban:
      description: "Unban a player."